INSERT INTO auto_script (script_name, script_desc, target_package, config, version, status, priority, execution_frequency, timeout, create_time) VALUES (
'抖音搜索播放-小玄宗大师兄',
'打开抖音搜索小玄宗大师兄，点击第一个图片进入播放，点击下一集，播放一半后上滑',
'com.ss.android.ugc.aweme',
'{"controls":[{"control_id":"btn_search","control_name":"搜索按钮","match_type":"text","match_value":"搜索","match_mode":"exact","operation":"click","delay_before":2000,"delay_after":1000,"retry_count":3},{"control_id":"input_search","control_name":"搜索输入框","match_type":"text","match_value":"搜索","match_mode":"contains","operation":"click","delay_before":500,"delay_after":500,"retry_count":3},{"control_id":"input_keyword","control_name":"输入搜索关键词","match_type":"class","match_value":"android.widget.EditText","match_mode":"exact","operation":"input","input_text":"小玄宗大师兄","delay_before":500,"delay_after":1000,"retry_count":3},{"control_id":"btn_search_submit","control_name":"搜索提交按钮","match_type":"text","match_value":"搜索","match_mode":"exact","operation":"click","delay_before":500,"delay_after":2000,"retry_count":3},{"control_id":"tab_image","control_name":"图片标签","match_type":"text","match_value":"图片","match_mode":"exact","operation":"click","delay_before":500,"delay_after":1500,"retry_count":3},{"control_id":"first_image_result","control_name":"第一个图片结果","match_type":"position","match_value":"first_image","match_mode":"exact","operation":"click","position":{"x_ratio":0.5,"y_ratio":0.35},"delay_before":1000,"delay_after":3000,"retry_count":3},{"control_id":"wait_for_video_load","control_name":"等待视频加载","match_type":"delay","operation":"wait","wait_time":3000,"delay_before":0,"delay_after":0,"retry_count":1},{"control_id":"btn_next_episode","control_name":"下一集按钮","match_type":"text","match_value":"下一集","match_mode":"exact","operation":"click","delay_before":1000,"delay_after":2000,"retry_count":5},{"control_id":"wait_half_play","control_name":"等待播放一半","match_type":"delay","operation":"wait","wait_time":15000,"delay_before":0,"delay_after":0,"retry_count":1},{"control_id":"swipe_up","control_name":"向上滑动屏幕","match_type":"gesture","operation":"swipe_up","swipe_config":{"start_x_ratio":0.5,"start_y_ratio":0.7,"end_x_ratio":0.5,"end_y_ratio":0.3,"duration":500},"delay_before":500,"delay_after":1000,"retry_count":1}],"conditions":[{"condition_id":"check_search_page","condition_type":"text_exists","condition_value":"搜索","true_branch":["input_search"],"false_branch":["btn_search"]},{"condition_id":"check_next_episode_exists","condition_type":"text_exists","condition_value":"下一集","true_branch":["btn_next_episode"],"false_branch":["wait_half_play"]}],"loop_config":{"loop_type":"count","loop_count":1,"loop_interval":1000},"record_config":{"base_fields":["start_time","end_time","status","duration"],"extend_fields":[{"field_name":"search_keyword","field_type":"string","field_desc":"搜索关键词"},{"field_name":"video_found","field_type":"boolean","field_desc":"是否找到视频"},{"field_name":"next_episode_clicked","field_type":"boolean","field_desc":"是否点击下一集"}]}}',
'1.0.0',
1,
2,
'once',
120,
NOW()
);
